CREATE TABLE IF NOT EXISTS evenement (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(60) NOT NULL,
    Description VARCHAR(512) NULL,
    Date DATETIME NOT NULL,
    DateCreation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Illustration BINARY(16) NULL,
    CreateurID BIGINT NOT NULL
);


